name = "StaticFloats"
uuid = "ac00224d-9075-48ad-b23d-c66f427693bb"
authors = ["chriselrod", "ChrisRackauckas", "Tokazama", "cscherrer"]
version = "0.1.0"

[deps]
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
Static = "0.7"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
